let sb;
const screen=document.getElementById('screen'),buttons=[...document.querySelectorAll('nav button[data-screen]')];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function setup(){const r=await fetch('/api/config'),c=await r.json();if(!c.supabaseUrl||!c.supabaseKey)throw new Error('GOVERNMENT backend is not configured yet.');sb=window.supabase.createClient(c.supabaseUrl,c.supabaseKey)}
async function me(){const {data}=await sb.auth.getUser();return data.user}
function render(n){buttons.forEach(b=>b.classList.toggle('active',b.dataset.screen===n));if(n==='home')home();if(n==='live')live();if(n==='create')create();if(n==='inbox')inbox();if(n==='profile')profile()}
async function home(){try{const {data:ps,error}=await sb.from('videos').select('id,user_id,caption,storage_path,created_at,profiles(username)').order('created_at',{ascending:false});if(error)throw error;screen.innerHTML='<div class="tabs"><button class="selected">For You</button><button>Following</button></div><section class="feed">'+(ps?.length?ps.map(p=>{const url=sb.storage.from('videos').getPublicUrl(p.storage_path).data.publicUrl;return '<article class="card"><video class="video-player" controls playsinline preload="metadata" src="'+url+'"></video><div class="info"><b>@'+esc(p.profiles?.username||'user')+'</b><div>'+esc(p.caption||'')+'</div><div class="actions"><button data-like="'+p.id+'">♡ Like</button><button data-comment="'+p.id+'">💬 Comment</button><button>↗ Share</button></div></div></article>'}).join(''):'<div class="empty">No videos yet. Be the first to post.</div>')+'</section>';document.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>like(b.dataset.like,b));document.querySelectorAll('[data-comment]').forEach(b=>b.onclick=()=>comment(b.dataset.comment))}catch(e){screen.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function like(id,b){const u=await me();if(!u)return auth();const {data}=await sb.from('video_likes').select('video_id').eq('video_id',id).eq('user_id',u.id).maybeSingle();if(data)await sb.from('video_likes').delete().eq('video_id',id).eq('user_id',u.id);else await sb.from('video_likes').insert({video_id:id,user_id:u.id});const {count}=await sb.from('video_likes').select('*',{count:'exact',head:true}).eq('video_id',id);b.textContent=(data?'♡ ':'♥ ')+(count||0)}
async function comment(id){const u=await me();if(!u)return auth();const text=prompt('Comment');if(!text)return;const {error}=await sb.from('video_comments').insert({video_id:id,user_id:u.id,body:text.slice(0,500)});if(error)alert(error.message);else alert('Comment added.')}
function live(){screen.innerHTML='<h2>🔴 LIVE</h2><p style="color:#888">LIVE streaming is the next major feature.</p>'}
function inbox(){screen.innerHTML='<h2>Inbox</h2><div class="live-card">💬 <b>Messages</b><p style="color:#888">Messaging will be connected next.</p></div>'}
async function create(){const u=await me();if(!u)return auth();screen.innerHTML='<h2>Create</h2><div class="form"><input class="input" id="caption" maxlength="120" placeholder="Write a caption..."><input class="input" id="videoFile" type="file" accept="video/mp4,video/webm,video/quicktime"><button class="primary" id="postVideo">Post video</button><p id="status" style="color:#888;text-align:center">Videos are stored permanently in GOVERNMENT cloud storage.</p></div>';document.getElementById('postVideo').onclick=async()=>{const f=document.getElementById('videoFile').files[0];if(!f)return status.textContent='Choose a video first.';if(f.size>500*1024*1024)return status.textContent='Video is over the 500 MB limit.';status.textContent='Uploading...';const path=u.id+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const {error:up}=await sb.storage.from('videos').upload(path,f,{contentType:f.type,upsert:false});if(up)return status.textContent=up.message;const {error}=await sb.from('videos').insert({user_id:u.id,caption:caption.value,storage_path:path});if(error){await sb.storage.from('videos').remove([path]);return status.textContent=error.message}home()}}
function auth(){screen.innerHTML='<div class="auth"><h2>Welcome to GOVERNMENT</h2><p style="color:#888">Use your GOVERNMENT account.</p><div class="tabs"><button id="loginTab" class="selected">Login</button><button id="regTab">Create account</button></div><div id="authForm"></div></div>';let mode='login';const draw=()=>{authForm.innerHTML=mode==='login'?'<div class="form"><input class="input" id="email" type="email" placeholder="Email"><input class="input" id="password" type="password" placeholder="Password"><button class="primary" id="submit">Login</button><p id="err" style="color:#ff6b6b"></p></div>':'<div class="form"><input class="input" id="username" placeholder="Username"><input class="input" id="email" type="email" placeholder="Email"><input class="input" id="password" type="password" placeholder="Password (6+ characters)"><button class="primary" id="submit">Create account</button><p id="err" style="color:#ff6b6b"></p></div>';submit.onclick=async()=>{err.textContent='';const r=mode==='login'?await sb.auth.signInWithPassword({email:email.value,password:password.value}):await sb.auth.signUp({email:email.value,password:password.value,options:{data:{username:username.value}}});if(r.error)return err.textContent=r.error.message;if(mode==='register'&&!r.data.session)return err.textContent='Account created. Check your email to confirm it, then log in.';profile()};};loginTab.onclick=()=>{mode='login';loginTab.className='selected';regTab.className='';draw()};regTab.onclick=()=>{mode='register';regTab.className='selected';loginTab.className='';draw()};draw()}
async function profile(){const u=await me();if(!u)return auth();const {data:p}=await sb.from('profiles').select('username,email').eq('id',u.id).maybeSingle();screen.innerHTML='<div class="row"><div class="avatar" style="width:72px;height:72px;font-size:24px">G</div><div><h2 style="margin:0">@'+esc(p?.username||u.user_metadata?.username||'user')+'</h2><span style="color:#888">'+esc(u.email||'')+'</span></div></div><button class="primary" id="logout">Log out</button>';logout.onclick=async()=>{await sb.auth.signOut();profile()}}
buttons.forEach(b=>b.onclick=()=>render(b.dataset.screen));
setup().then(()=>render('home')).catch(e=>{screen.innerHTML='<div class="empty">'+esc(e.message)+'</div>'});