const screen=document.getElementById('screen'),buttons=[...document.querySelectorAll('nav button[data-screen]')];let liked=false;
const getToken=()=>localStorage.getItem('gov_token');
async function api(url,opts={}){opts.headers={'Content-Type':'application/json',...(opts.headers||{})};if(getToken())opts.headers.Authorization='Bearer '+getToken();const r=await fetch(url,opts),d=await r.json();if(!r.ok)throw new Error(d.error||'Something went wrong');return d}
function render(name){buttons.forEach(b=>b.classList.toggle('active',b.dataset.screen===name));if(name==='home')home();if(name==='live')live();if(name==='create')create();if(name==='inbox')inbox();if(name==='profile')profile()}
function home(){screen.innerHTML='<div class="tabs"><button class="selected">For You</button><button>Following</button></div><section class="feed"><article class="card"><div class="video">▶<small>GOVERNMENT • Welcome to the future</small></div><div class="info"><div class="row"><div class="avatar">G</div><div><b>@government</b><div style="color:#888;font-size:13px">Welcome to GOVERNMENT</div></div></div><div class="actions"><button id="like">♡ 12.4K</button><button>💬 843</button><button>↗ Share</button></div></div></article></section>';document.getElementById('like').onclick=()=>{liked=!liked;document.getElementById('like').textContent=liked?'♥ 12.5K':'♡ 12.4K'}}
function live(){screen.innerHTML='<h2>🔴 LIVE</h2><p style="color:#888">Discover live creators and join their rooms.</p><div class="live-grid"><div class="live-card"><div class="row"><div class="avatar">A</div><div><b>Abuja Vibes</b><div class="live-dot">● LIVE · 2.8K watching</div></div></div><p>Music, chat and community.</p><button class="primary">Join LIVE</button></div></div>'}
function create(){screen.innerHTML='<h2>Create</h2><div class="form"><button class="primary">📹 Upload a video</button><button class="primary">🔴 Start a LIVE</button></div>'}
function inbox(){screen.innerHTML='<h2>Inbox</h2><div class="live-card">💬 <b>Messages</b><p style="color:#888">Your conversations will appear here.</p></div><div class="live-card" style="margin-top:12px">🔔 <b>Notifications</b><p style="color:#888">Likes, follows, gifts and LIVE alerts.</p></div>'}
async function profile(){if(!getToken()){auth();return}try{const d=await api('/api/me');screen.innerHTML='<div class="row"><div class="avatar" style="width:72px;height:72px;font-size:24px">G</div><div><h2 style="margin:0">@'+d.user.username+'</h2><span style="color:#888">'+d.user.email+'</span></div></div><div class="live-card" style="margin-top:18px"><div class="row" style="justify-content:space-around"><b>0<br><small>Following</small></b><b>0<br><small>Followers</small></b><b>0<br><small>Likes</small></b></div></div><button class="primary" id="logout">Log out</button>';document.getElementById('logout').onclick=async()=>{await api('/api/logout',{method:'POST'});localStorage.removeItem('gov_token');profile()}}catch(e){localStorage.removeItem('gov_token');auth()}}
function auth(){screen.innerHTML='<div class="auth"><h2>Welcome to GOVERNMENT</h2><p style="color:#888">Create your account or sign in.</p><div class="tabs"><button id="loginTab" class="selected">Login</button><button id="registerTab">Create account</button></div><div id="authForm"></div></div>';let mode='login';const draw=()=>{document.getElementById('authForm').innerHTML=mode==='login'?'<div class="form"><input class="input" id="email" type="email" placeholder="Email"><input class="input" id="password" type="password" placeholder="Password"><button class="primary" id="submit">Login</button><p id="err" style="color:#ff6b6b"></p></div>':'<div class="form"><input class="input" id="username" placeholder="Username"><input class="input" id="email" type="email" placeholder="Email"><input class="input" id="password" type="password" placeholder="Password (6+ characters)"><button class="primary" id="submit">Create account</button><p id="err" style="color:#ff6b6b"></p></div>';document.getElementById('submit').onclick=async()=>{const b={email:email.value,password:password.value};if(mode==='register')b.username=username.value;try{const d=await api('/api/'+mode,{method:'POST',body:JSON.stringify(b)});localStorage.setItem('gov_token',d.token);profile()}catch(e){document.getElementById('err').textContent=e.message}}};loginTab.onclick=()=>{mode='login';loginTab.className='selected';registerTab.className='';draw()};registerTab.onclick=()=>{mode='register';registerTab.className='selected';loginTab.className='';draw()};draw()}
buttons.forEach(b=>b.onclick=()=>render(b.dataset.screen));render('home');